---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(reactable)
library(dplyr)
library(tidyr)

options(box.path = here::here())

box::use(tablas = data / mocked / matriz[balances = balance_matriz, diferencias])
```

```{r}
tablas$balance_matriz |>
  mutate(across(where(is.numeric), \(x) round(x, 2))) |> 
  reactable(
    defaultColDef = colDef(headerClass = "header"),
    columns = list(
      sector = colDef(name = "", class = "header")
    ),
    class = "matrix",
    highlight = TRUE,
    sortable = FALSE
  )
```

```{r}

diferencias_table <- diferencias |>
  mutate(
    across(4, \(x) x * 100),
    across(where(is.numeric), \(x) round(x, 2))
  )

total <- diferencias_table |> 
  filter(sector == "total") |>
  mutate(sector = stringr::str_to_title(sector))

diferencias_table |>
  filter_out(sector == "total") |> 
  reactable(
    class = "matrix",
    defaultColDef = colDef(
      headerClass = "header", 
      footer = \(values, col) total[[col]],
      footerStyle = list(fontWeight = "bold")
    ),
    columns = list(
      sector = colDef(name = "Sector")
    )
  )
```

```{css}
.matrix {
  margin-top: 1rem;
  font-size: 1.2rem;
  border: 1px solid hsl(213, 33%, 93%);
  border-radius: 4px;
  box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.1);
}

.header,
.matrix .rt-tbody .rt-td.header {
  background-color: hsl(213, 45%, 97%);
  border-bottom-color: hsl(213, 33%, 93%);
  border-bottom-width: 1px;
  color: hsl(213, 13%, 33%);
  font-weight: 600;
}

.header[aria-sort]:hover,
.header[aria-sort]:focus {
  color: hsl(213, 55%, 50%);
}
```

